# Generated by Django 3.1.6 on 2021-02-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
    ]
