# Generated by Django 3.1.6 on 2021-02-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20210218_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attr_type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('datetime', 'Datetime'), ('bool', 'Boolean')], default='str', max_length=8),
        ),
    ]
