# Generated by Django 3.1.6 on 2021-02-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20210218_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
